# Use Maven to build the application.
FROM maven:3.9.6-amazoncorretto-21-al2023 AS build
WORKDIR /app
COPY pom.xml .
RUN mvn dependency:go-offline
COPY src ./src
RUN mvn clean package -DskipTests
# Use Amazon Corretto JDK 21 as the runtime image.
FROM amazoncorretto:21-alpine-jdk
LABEL maintainer="robison.torres21@gmail.com"
RUN addgroup -S spring && adduser -S spring -G spring
USER spring:spring
WORKDIR /app
COPY --from=build /app/target/*.jar marketplace.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "marketplace.jar"]